### ISSUE TITLE
Protect container with basic authentification

### ISSUE THREAD

**Issue by yousefchtourou** [budtmo/docker-android#194]
## 💬 Questions and Help

Any idea to protect this container ? 

any body in LAN , 
![emulator_samsung_galaxy_s6](https://user-images.githubusercontent.com/45118325/63649049-ac06df80-c730-11e9-95aa-b486631ec969.png)
can press Ctrl+alt+supper to shutdown the emulator and fail the application

**Comment by Arne-B** [comment]
Yeah, NoVNC uses websockify to provide a webserver. Websockify supports auth plugins, but the noVNC start script does not use this feature (as far as i could tell in a quick check). (${WEBSOCKIFY} ${SSLONLY} --web ${WEB} ${CERT:+--cert ${CERT}} ${KEY:+--key ${KEY}} ${PORT} ${VNC_DEST} ${RECORD_ARG} &)
This means, that this script from noVNC needs to be changed first, before support could be added in this project.

**Comment by ychtourou** [comment]
protect by basic authentification for example

**Comment by Arne-B** [comment]
setting a vnc password with 
RUN mkdir /root/.vnc/ \
 && x11vnc -storepasswd password /root/.vnc/passwd

and running vnc with 
command=/usr/bin/x11vnc -display %(ENV_DISPLAY)s -usepw -forever -shared

would make sure, that every vnc access it at least secure by a global default password which then must be changed at runtime.
I would suggest to introduce some ENV VAR which, if set, sets the vnc password and enables it.
The default can still be no password, because its an active choice to forward the vnc ports and enable external access.

**Comment by budtmo** [comment]
Hi @ychtourou, 

I dont give it, because it make easier to integrate with other tools (e.g. zalenium) and easier for user to open it (the user do not need to give the credentials everytime they want to see what happening and for testing purpose in my opinion it should be secured enough because you are in the same company network). probably the easiest solution is that you dont need to open any the vnc port and use screen recording if you want to see what happening during test execution. but you can share your use case why you want to protect the container in the same network, so maybe we can discuss the next step.  

I will close it for now, but feel free to reopen it.
